<a href="https://colab.research.google.com/github/Felesia302/GameOfLife/blob/main/01-Intro%20and%20knn/hw/hw.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Домашнее задание 1.

В этой домашке запрещается использовать циклы. Все задачи должны быть выполнены с помощью внутренних функций numpy и pandas. Не используй AI при решении, попробуй всё сделать сам. Это не сложно :)

In [6]:
import numpy as np
import pandas as pd
from numpy.testing import assert_equal, assert_array_equal
from pandas.testing import assert_frame_equal

# Ближайший элемент

Реализуйте функцию, принимающую на вход непустой тензор (может быть многомерным) $X$ и некоторое число $a$ и возвращающую ближайший к числу элемент тензора. Если ближайших несколько - выведите минимальный из ближайших. (Вернуть нужно само число, а не индекс числа!)

### Sample
#### Input:
```python
X = np.array([[ 1,  2, 13],
              [15,  6,  8],
              [ 7, 18,  9]])
a = 7.2
```
#### Output:
```python
7
```

# TASK

In [7]:
import numpy as np


def nearest_value(X: np.ndarray, a: float) -> np.float64:
    diff = np.abs(X - a)
    closest_elements = X[diff == np.min(diff)]
    return np.float64(np.min(closest_elements))

In [8]:
######################################################
assert_equal(
    nearest_value(np.array([ 1,  2, 13]), 10),
    13)
######################################################
assert_equal(
    nearest_value(np.array([ -1,  0]), -0.5),
    -1)
######################################################
assert_equal(
    nearest_value(np.array([[[ 1], [2],[3]],[[4],[5],[6]]]), 4.5),
    4)
######################################################
assert_equal(
    nearest_value(np.array([[ 1,  2, 13],
                            [15,  6,  8],
                            [ 7, 18,  9]]), 7.2),
    7)
######################################################
assert_equal(
    nearest_value(np.array([[ -1,  -2],
                            [-15,  -6]]), -100),
    -15)
######################################################
assert_equal(
    nearest_value(np.array([[ 2,  2],
                            [12,  12]]), 7),
    2)
######################################################
assert_equal(
    nearest_value(np.array([[ -2,  -2],
                            [-12,  -12]]), -7),
    -12)
######################################################

# Сортировка чисел

Дан одномерный массив целых чисел. Необходимо отсортировать в нем только числа, которые делятся на $2$. При этом начальный массив изменять нельзя.

### Sample
#### Input:
```python
A = np.array([43, 66, 34, 55, 78, 105, 2])
```
#### Output:
```python
array([ 43,   2,  34,  55,  66, 105,  78])
```


# TASK

In [9]:
def sort_evens(A: np.ndarray) -> np.ndarray:
    res = A.copy()
    even_mask = (res % 2 == 0)
    res[even_mask] = np.sort(res[even_mask])
    return res

In [10]:
######################################################
assert_array_equal(sort_evens(np.array([])), np.array([]))
######################################################
assert_array_equal(sort_evens(np.array([2, 0])), np.array([0, 2]))
######################################################
assert_array_equal(sort_evens(np.array([9, 3, 1, 5, 7])), np.array([9, 3, 1, 5, 7]))
######################################################
assert_array_equal(sort_evens(np.array([8, 12, 4, 10, 6, 2])), np.array([2, 4, 6, 8, 10, 12]))
######################################################

# Страшные маски

Даны трехмерный тензор размерности $X(n, k, k)$, состоящий из $0$ или $1$, или $n$ картинок $k \times k$. Нужно применить к нему указанную маску размерности $(k, k)$: В случае, если биты в маске и картинке совпадают, то результирующий бит должен быть равен $0$, иначе $1$.

### Sample
#### Input:
```python
X = np.array([
              [[ 1, 0, 1],
               [ 1, 1, 1],
               [ 0, 0, 1]],
             
              [[ 1, 1, 1],
               [ 1, 1, 1],
               [ 1, 1, 1]]
            ])
mask = np.array([[1, 1, 0],
                 [1, 1, 0],
                 [1, 1, 0]])
```
#### Output:
```python
array([[[0, 1, 1],
        [0, 0, 1],
        [1, 1, 1]],

       [[0, 0, 1],
        [0, 0, 1],
        [0, 0, 1]]])
```


# TASK

In [11]:
import numpy as np


def tensor_mask(X: np.ndarray, mask: np.ndarray) -> np.ndarray:
    return (X ^ mask).astype(X.dtype)

In [12]:
######################################################
X = np.zeros(9, dtype=int).reshape((1,3,3))
mask = np.zeros(9, dtype=int).reshape((3,3))
assert_array_equal(tensor_mask(X, mask), np.zeros(9, dtype=int).reshape((1,3,3)))
######################################################
X = np.zeros(9*3, dtype=int).reshape((3,3,3))
mask = np.ones(9, dtype=int).reshape((3,3))
assert_array_equal(tensor_mask(X, mask), np.ones(9*3, dtype=int).reshape((3,3,3)))
######################################################
X = np.array([[[ 1, 0, 1],
               [ 1, 1, 1],
               [ 0, 0, 1]]])
mask = np.array([[1, 1, 0],
                 [1, 1, 0],
                 [1, 1, 0]])
assert_array_equal(tensor_mask(X, mask),
                   np.array([[[0, 1, 1],
                             [0, 0, 1],
                             [1, 1, 1]]]))
######################################################

# Сумма цифр в массиве

На вход подается `np.ndarray` c натуральными числами. Надо получить массив сумм цифр в этих числах.

### Sample
#### Input:
```python
a = np.array([1241, 354, 121])
```
#### Output:
```python
array([ 8, 12, 4])
```


# TASK

In [13]:
import numpy as np


def num_sum(a: np.ndarray) -> np.ndarray:
    s = a.astype(str)

    return np.array([
        np.fromiter(map(int, num), dtype=int).sum()
        for num in s
    ])

In [14]:
######################################################
assert_array_equal(num_sum(np.array([82])), np.array([10]))
######################################################
assert_array_equal(num_sum(np.array([1241, 354, 121])), np.array([ 8, 12, 4]))
######################################################
assert_array_equal(num_sum(np.array([1, 22, 333, 4444, 55555])), np.array([1, 4, 9, 16, 25]))
######################################################

# Чистка NaN-ов

Одна из важных проблем данных - пустые значения. В *numpy* и *pandas* они обычно объявляются специальным типом ```np.nan```. В реальных задачах нам часто нужно что-то сделать с этими значениями. Например заменить на 0, среднее или медиану.

Реализуйте функцию, которая во входной вещественной матрице ```X``` находит все значения ```nan``` и заменяет их на **медиану** остальных элементов столбца. Если все элементы столбца матрицы ```nan```, то заполняем столбец нулями.

### Sample
#### Input:
```python
X = np.array([[np.nan,      4,  np.nan],
              [np.nan, np.nan,       8],
              [np.nan,      5,  np.nan]])
```
#### Output:
```python
array([[0. , 4. , 8. ],
       [0. , 4.5, 8. ],
       [0. , 5. , 8. ]])
```


# TASK

In [15]:
import numpy as np
import pandas as pd


def replace_nans(X: np.ndarray) -> np.ndarray:
    res = np.array(X, copy=True, dtype=float)

    for i in range(res.shape[1]):
        column = res[:, i]
        mask = np.isnan(column)

        if np.any(mask):
            if not np.all(mask):
                median_val = np.nanmedian(column)
            else:
                median_val = 0.0

            res[mask, i] = median_val

    return res

In [16]:
from numpy.testing import assert_array_equal, assert_array_almost_equal
######################################################
assert_array_equal(replace_nans(
    np.array([[np.nan], [np.nan],  [np.nan]])),
    np.array([[0. ],[ 0. ],[ 0. ]])
)
######################################################
assert_array_equal(replace_nans(
    np.array([[0, 42,  42]])),
    np.array([[0, 42 , 42]])
)
######################################################
assert_array_equal(replace_nans(
    np.array([[np.nan], [1], [np.nan]])),
    np.array([[1.] ,[ 1.] ,[ 1. ]])
)
######################################################
assert_array_equal(replace_nans(
    np.array([[4], [1],  [np.nan]])),
    np.array([[4 ], [1] ,[ 2.5]])
)
######################################################
assert_array_equal(replace_nans(
    np.array([[np.nan, np.nan,  np.nan],
              [     4, np.nan,       5],
              [np.nan,      8,  np.nan]]).T),
    np.array([[0. , 0. , 0. ],
              [4. , 4.5, 5. ],
              [8. , 8. , 8. ]]).T
)
######################################################

# Бухгалтерия зоопарка

Вам на вход подается словарь, где ключ - это тип животного, а значение - словарь с признаками этого животного, где ключ - тип признака, а значение - значение признака (Типичный json проще говоря). Наименования признаков животного - всегда строки. Значения признаков - любой из типов pandas.

Вам следует создать табличку, где по строчкам будут идти животные, а по колонкам - их признаки, которая удовлетворяет следующим условиям:

* Тип животного нужно выделить в отдельную колонку `Type`
* Строки отсортированы по типу животного в алфавитном порядке
* Колонки отсортированы в алфавитном порядке, кроме колонки `Type` - она первая
* Индексы строк - ряд натуральных чисел начиная с 0 без пропусков

Имейте в виду, что признаки у двух животных могут не совпадать, значит незаполненные данные нужно заполнить `Nan` значением.

Верните на выходе табличку(`DataFrame`), в которой отсутствуют Nan значения. При этом могут отсутствовать некоторые признаки, но животные должны присутствовать **все**. Изначальные типы значений из словаря: `int64`, `float64`, `bool` и.т.д. должны сохраниться и в конечной табличке, а не превратиться в `object`-ы. (От удаляемых признаков этого, очевидно, не требуется).

### Sample 1
#### Input:
```python
ZOO = {
        'cat':{'color':'black', 'tail_len': 50, 'injured': False},
        'dog':{'age': 6, 'tail_len': 30.5, 'injured': True}
      }
```
#### Output:

|  | Type | injured |tail_len |
|--|----|--------|-------|
|0 | cat |  False | 50.0 |
|1 | dog |  True  | 30.5  |


# TASK

In [24]:
import pandas as pd
import numpy as np


def get_zoo_table(zoo: dict) -> pd.DataFrame:
    df = pd.DataFrame.from_dict(zoo, orient='index')
    df['Type'] = df.index

    df = df.sort_values('Type').reset_index(drop=True)

    cols = sorted([c for c in df.columns if c != 'Type'])
    df = df[['Type'] + cols]
    df = df.dropna(axis=1)

    return df

In [25]:
######################################################
ZOO = {
        'cat': {'color':'black', 'tail_len': 50.0, 'injured': False},
        'dog': {'age': 6, 'tail_len': 30.5, 'injured': True}
      }
answer = pd.DataFrame(
    {
     'Type':['cat', 'dog'],
     'injured':[False, True],
     'tail_len':[50.0, 30.5]
    }
)
df = ZOOtable(ZOO)

assert_frame_equal(
    df.reset_index(drop=True),
    answer
)
######################################################
ZOO = {
        'cat': {'color':'black'},
        'dog': {'age': 6}
      }
answer = pd.DataFrame(
    {
     'Type':['cat', 'dog']
    }
)

df = ZOOtable(ZOO)

assert_frame_equal(
    df.reset_index(drop=True),
    answer
)
######################################################

# Простые преобразования

На вход подается `DataFrame` из 3-х колонок дата рождения и смерти человека на **русском** языке в формате представленом ниже:

|  | Имя             | Дата рождения  | Дата смерти      
|--|-----------------|----------------|------------------
|0 |Никола Тесла     |10 июля 1856 г. |7 января 1943 г.  
|1 |Альберт Эйнштейн |14 марта 1879 г.|18 апреля 1955 г.  

Необходимо вернуть исходную таблицу с добавленным в конце столбцом полных лет жизни.


|  | Имя             | Дата рождения  | Дата смерти     | Полных лет
|--|-----------------|----------------|-----------------|-----------
|0 |Никола Тесла     |10 июля 1856 г. |7 января 1943 г. | 86        
|1 |Альберт Эйнштейн |14 марта 1879 г.|18 апреля 1955 г.| 76        

Формат даты единый, исключений нет, пробелы мужду элементами дат присутствуют, исключений (`Nan`) нету.

P.S. Для обработки высокосных годов используйте модуль `dateutil.relativedelta`.

# TASK

In [19]:
import numpy as np
import pandas as pd


def rus_feature(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()

    months = {
        'января': '01', 'февраля': '02', 'марта': '03',
        'апреля': '04', 'мая': '05', 'июня': '06',
        'июля': '07', 'августа': '08', 'сентября': '09',
        'октября': '10', 'ноября': '11', 'декабря': '12'
    }

    def convert(series):
        s = series.str.replace(' г.', '', regex=False)
        parts = s.str.split(' ', expand=True)
        day = parts[0].str.zfill(2)
        month = parts[1].map(months)
        year = parts[2]
        return pd.to_datetime(year + '-' + month + '-' + day)

    birth = convert(df['Дата рождения'])
    death = convert(df['Дата смерти'])

    years = death.dt.year - birth.dt.year
    before_birthday = (
        (death.dt.month < birth.dt.month) |
        ((death.dt.month == birth.dt.month) & (death.dt.day < birth.dt.day))
    )

    df['Полных лет'] = years - before_birthday.astype(int)

    return df

In [20]:
######################################################
names = pd.DataFrame({'Имя':['Никола Тесла', 'Альберт Эйнштейн'],
                   'Дата рождения':['10 июля 1856 г.','14 марта 1879 г.'],
                   'Дата смерти':  ['7 января 1943 г.', '18 апреля 1955 г.']})
answer = pd.DataFrame({'Имя':['Никола Тесла', 'Альберт Эйнштейн'],
                       'Дата рождения':['10 июля 1856 г.','14 марта 1879 г.'],
                       'Дата смерти':  ['7 января 1943 г.', '18 апреля 1955 г.'],
                       'Полных лет':[86, 76]})
assert_frame_equal(
    rus_feature(names),
    answer
)
######################################################
names = pd.DataFrame({'Имя':['Никола Тесла'],
                   'Дата рождения':['10 июля 1856 г.'],
                   'Дата смерти':  ['7 января 1857 г.']})
answer = pd.DataFrame({'Имя':['Никола Тесла'],
                       'Дата рождения':['10 июля 1856 г.'],
                       'Дата смерти':  ['7 января 1857 г.'],
                       'Полных лет':[0]})
assert_frame_equal(
    rus_feature(names),
    answer
)
######################################################
names = pd.DataFrame({'Имя':['Никола Тесла'],
                   'Дата рождения':['1 января 2000 г.'],
                   'Дата смерти':  ['31 декабря 2000 г.']})
answer = pd.DataFrame({'Имя':['Никола Тесла'],
                       'Дата рождения':['1 января 2000 г.'],
                       'Дата смерти':  ['31 декабря 2000 г.'],
                       'Полных лет':[0]})
assert_frame_equal(
    rus_feature(names),
    answer
)

# Характеристики

В этой задаче на вход подаются всем известные данные о погибших/выживших пассажирах на титанике. (Файл `titanic_train.csv` в [папке data](https://github.com/AlexanderZiyatdinov/ML2025-2026_local/blob/main/01-Intro%20and%20knn/data/titanic_train.csv)).

Верните среднее, медиану, максимальное и минимальное значение возраста **погибших** мужчин. Именно в данном порядке.

### Sample 1
#### Input:
```python
df = pd.read_csv('titanic_train.csv', index_col='PassengerId')
```
#### Output:
```python
return 42,42,42,42
```

# TASK

In [21]:
import pandas as pd


def men_stat(df: pd.DataFrame) -> tuple[float, float, float, float]:
    dead_men_ages = df[(df['Sex'] == 'male') & (df['Survived'] == 0)]['Age']

    mean_age = float(dead_men_ages.mean())
    median_age = float(dead_men_ages.median())
    max_age = float(dead_men_ages.max())
    min_age = float(dead_men_ages.min())

    return mean_age, median_age, max_age, min_age

# Сводная таблица

В этой задаче на вход подаются всем известные данные о погибших/выживших пассажирах на титанике. (Файл `titanic_train.csv` в [папке data](https://github.com/AlexanderZiyatdinov/ML2025-2026_local/blob/main/01-Intro%20and%20knn/data/titanic_train.csv)).

Сделать сводную таблицу по **медианному возрасту** для пола и класса. Для примера посмотрите сводную таблицу по сумме выживших, для пола и класса.

| Sex        | Pclass  | Survived |
|------------|---------|----------|
| **female** | **1**   |      91  |
|            | **2**   |      70  |
|            | **3**   |      72  |
| **male**   | **1**   |      45  |
|            | **2**   |      17  |
|            | **3**   |      47  |

Обратите внимание, что первые 2 столбца - это не колонки, а `MultiIndex`.

### Sample 1
#### Input:
```python
df = pd.read_csv('titanic_train.csv', index_col='PassengerId')
```

# TASK

In [22]:
import pandas as pd


def age_stat(df: pd.DataFrame) -> pd.DataFrame:
    table = df.pivot_table(values='Age', index='Sex', columns='Pclass', aggfunc='median')
    return table

# Популярные девушки

В этой задаче на вход подаются всем известные данные о погибших/выживших пассажирах на титанике. (Файл `titanic_train.csv` в [папке data](https://github.com/AlexanderZiyatdinov/ML2025-2026_local/blob/main/01-Intro%20and%20knn/data/titanic_train.csv)).

Выведите список имен незамужних женщин(`Miss`) отсортированный по популярности.

* В полном имени девушек **имя** - это **первое слово без скобок** после `Miss`.
* Остальные строки не рассматриваем.
* Девушки с одинаковой популярностью сортируются по имени в алфавитном порядке.

**Слово/имя** - подстрока без пробелов.
**Популярность** - количество таких имен в таблице.

### Sample 1
#### Input:
```python
data = pd.read_csv('titanic_train.csv', index_col='PassengerId')
```
#### Output:
Вот начало данного списка. Заметьте, **названия колонок должны совпадать**

|  | Name | Popularity |
|--|----|--------|
|0 |Anna |9|
|1 |Mary |9
|2 |Margaret|6
|3 |Elizabeth|5
|4 |Alice |4
|5 |Bertha |4
|6 |Ellen |4
|7 |Helen |4


# TASK

In [23]:
import pandas as pd


def fename_stat(df: pd.DataFrame) -> pd.DataFrame:
    miss_df = df[df['Name'].str.contains('Miss.', regex=False)].copy()

    def get_first_name(full_name):
        after_miss = full_name.split('Miss. ')[1]
        first_name = after_miss.split(' ')[0]
        return first_name.replace('(', '').replace(')', '').replace('"', '')

    miss_df['Name'] = miss_df['Name'].apply(get_first_name)

    result = miss_df['Name'].value_counts().reset_index()
    result.columns = ['Name', 'Popularity']

    result = result.sort_values(by=['Popularity', 'Name'], ascending=[False, True])

    return result.reset_index(drop=True)